### ISSUE TITLE
HTTP 404 for get-file (with --binary) and files having `+` in path

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#161]
Related to https://github.com/retz/retz/issues/79

I have a file with a `+` in the file name created by one of my jobs. I can list it and download it with `get-file`, but not when I use the `--binary` option:

```
$ ./bin/retz-client -C retz.properties list-files --id 1677 --path results                    
Using jar file 'retz-client/build/libs/retz-client-0.2.8-SNAPSHOT-all.jar'
INFO gid  mode       uid     mtime               size path    
INFO 1000 -rw-r--r-- deepmux 2017-07-05 11:36:08 5    a+b.txt 

$ ./bin/retz-client -C retz.properties get-file --id 1677 --path results/a+b.txt                
Using jar file 'retz-client/build/libs/retz-client-0.2.8-SNAPSHOT-all.jar'
hoge

$ ./bin/retz-client -C retz.properties get-file --id 1677 --path results/a+b.txt --binary -R .
Using jar file 'retz-client/build/libs/retz-client-0.2.8-SNAPSHOT-all.jar'
INFO Binary mode: ignoring offset and length but downloading while file to './results/a+b.txt'.
INFO Fetching http://mesos3:9090/job/1677/download?path=results/a+b.txt
ERROR java.io.FileNotFoundException: http://mesos3:9090/job/1677/download?path=results/a+b.txt
java.io.FileNotFoundException: http://mesos3:9090/job/1677/download?path=results/a+b.txt
	at io.github.retz.web.Client.getBinaryFile(Client.java:178)
	at io.github.retz.web.ClientHelper.getWholeBinaryFile(ClientHelper.java:208)
	at io.github.retz.cli.CommandGetFile.handle(CommandGetFile.java:103)
	at io.github.retz.cli.Launcher.execute(Launcher.java:78)
	at io.github.retz.cli.Launcher.main(Launcher.java:56)
```

**Comment by kuenishi** [comment]
With 0.2.10 this should be fixed. Feel free to reopen if any further issues.
