### ISSUE TITLE
Move onto spotbugs from findbugs

### ISSUE THREAD

**Issue by kuenishi** [retz/retz#189]
With JDK9 `./gradlew findbugsMain` . Other tasks all work nicely.

```
 $ ./gradlew findbugsMain
                                          
> Task :retz-common:findbugsMain
Warning: Unknown version of Java
edu.umd.cs.findbugs.JavaVersionException: Could not parse Java version string: 9
        at edu.umd.cs.findbugs.JavaVersion.<init>(JavaVersion.java:68)                                                                                                                             
        at edu.umd.cs.findbugs.JavaVersion.<clinit>(JavaVersion.java:44)
        at edu.umd.cs.findbugs.DetectorFactory.isEnabledForCurrentJRE(DetectorFactory.java:248)
        at edu.umd.cs.findbugs.FindBugs.isDetectorEnabled(FindBugs.java:256)
```

The fix would be easy, but [findbugs is no longer an active project](https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2017-September/004383.html). [Spotbugs](https://spotbugs.github.io/) is the successor. Spotbugs is supposed to support JDK9, bug with 3.1.0-RC5 it does not work because of https://github.com/spotbugs/spotbugs/issues/320 . Although it is already reverted, it is not yet released. Logs for spotbugs is [here](https://gist.github.com/kuenishi/120f33acfb645b000f4906fdde5c3109).

Until this issue solved we can't move onto JDK9. Or possibly seek for static code analysis like [PMD](https://pmd.github.io/)? Thoughts?

Diff for spotbugs:

```diff
 $ git diff
diff --git a/build.gradle b/build.gradle
index 8e98d49..d5372b9 100644
--- a/build.gradle
+++ b/build.gradle
@@ -10,6 +10,7 @@ buildscript {
         classpath "com.github.jengelman.gradle.plugins:shadow:2.0.1"
         classpath 'com.netflix.nebula:gradle-ospackage-plugin:4.4.+'
         classpath "gradle.plugin.nl.javadude.gradle.plugins:license-gradle-plugin:0.14.0"
+        classpath "gradle.plugin.com.github.spotbugs:gradlePlugin:1.3"
     }
 }

@@ -42,10 +43,10 @@ allprojects {
 }

 subprojects {
-    apply plugin: 'jacoco'
+    //apply plugin: 'jacoco'
     apply plugin: 'scala'
     apply plugin: 'eclipse'
-    apply plugin: 'findbugs'
+    apply plugin: 'com.github.spotbugs'
     apply plugin: 'checkstyle'
     apply plugin: 'maven'
     apply plugin: 'maven-publish'
@@ -96,6 +97,7 @@ subprojects {
         }
     }

+    /*
     jacocoTestReport {
         reports {
             html.enabled = true
@@ -103,7 +105,7 @@ subprojects {
             csv.enabled = false
             html.destination file("${buildDir}/reports/jacoco")
         }
-    }
+    } */

     checkstyle {
         toolVersion = "8.1"
@@ -236,7 +238,8 @@ project(':retz-server') {

     mainClassName = 'io.github.retz.scheduler.Launcher'

-    findbugs.excludeFilter = file("config/findbugs/excludeFilter.xml")
+    //findbugs.excludeFilter = file("config/findbugs/excludeFilter.xml")
+    //spotbugs.excludeFilter = file("config/findbugs/excludeFilter.xml")

     ospackage {
         os = LINUX
```

**Comment by KengoTODA** [comment]
SpotBugs gradle plugin v1.3 has bug, please use v1.2 or v1.4 which will be released soon. 🙇

**Comment by kuenishi** [comment]
@KengoTODA I updated to 1.6 and it's working great. Thanks!
