### ISSUE TITLE
server side: Timeout on Read

### ISSUE THREAD

**Issue by kuenishi** [retz/retz#19]
In some cases where the agent has few free memory, and all-in-one mixed setup (server, client, Mesos master and agent), connection between client and server sometimes gets lost by timeout on read at server side. Server is supposed to be sending PING message in WebSocket every 20 seconds  but it happens.

```
2016-08-26 14:07:53.075 DEBUG [Scheduler-212035163] o.e.j.w.c.events.AbstractEventDriver - incomingError(java.net.SocketTimeoutException)
java.net.SocketTimeoutException: Timeout on Read
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:559)
        at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:149)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:514)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:251)
        at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:125)
        at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:157)
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
        at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-08-26 14:07:53.075 DEBUG [Scheduler-212035163] o.e.j.w.c.i.AbstractWebSocketConnection - close(1001,Idle Timeout)
```

**Comment by kuenishi** [comment]
Server is not reading from WebSocket any more after most APIs moved away from WebSocket
