### ISSUE TITLE
non-authentication mode is broken

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#61]
I am trying to run the retz server without authentication, so I set `retz.authentication = false` in both client and server, but still I get 401 when executing `./bin/retz-client -C retz.properties list-app`. (It works fine if I set `retz.authentication = true` with access key and secret on both server and client.) I was wondering whether the server looks at the `retz.authentication` value at all, so I removed access key/secret from the server, but then I get

```
2016-11-01 13:58:56.217 WARN  [main] io.github.retz.cli.FileConfiguration - Authentication is disabled
2016-11-01 13:58:56.220 INFO  [main] io.github.retz.cli.FileConfiguration - Mesos master=mesos3:5050, principal=retz, role=retz, retz.max.running=128, retz.executor.java=java, retz.database.url=jdbc:h2:mem:retz-server;DB_CLOSE_DELAY=-1, retz.max.stock=16
2016-11-01 13:58:56.225 INFO  [main] io.github.retz.scheduler.Launcher - Binding as http://localhost:9090
2016-11-01 13:58:56.450 INFO  [main] io.github.retz.db.Database - Initializing database jdbc:h2:mem:retz-server;DB_CLOSE_DELAY=-1
2016-11-01 13:58:56.615 INFO  [main] io.github.retz.db.Database - Checking database schema of jdbc:h2:mem:retz-server;DB_CLOSE_DELAY=-1 ...
2016-11-01 13:58:56.678 INFO  [main] io.github.retz.db.Database - No table exists: creating...
Exception in thread "main" java.lang.RuntimeException: Key cannot be null....
	at io.github.retz.cli.FileConfiguration.getUser(FileConfiguration.java:239)
	at io.github.retz.db.Database.init(Database.java:85)
	at io.github.retz.scheduler.Launcher.run(Launcher.java:68)
	at io.github.retz.scheduler.Launcher.main(Launcher.java:57)
```

**Comment by kuenishi** [comment]
Currently `Authorization` header may be lacking depending on client configuration, which confuses server side client identification. The fix will be:
- Servers always require Authorization header, never allows anonymous access
- Clients must send requests with Authorization header at least specifying user name from `retz.access.key`
- Signature is required for every request, but it'll be checked when the server has `retz.authentication = true`, while it's just _not checked_ when `retz.authentication = false` .

**Comment by kuenishi** [comment]
Although https://github.com/retz/retz/commit/df8e7cf62644d5d0b1f2e924024ea8f9f3f85e56 includes several copy and pastes, it fixes this issue.

**Comment by tgpfeiffer** [comment]
Checked to work as described above, but I made some suggestions for error reporting in #99 .
