### ISSUE TITLE
handle missing retz.access.key gracefully

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#99]
At the moment, if no `retz.access.key` is specified, the retz server fails with

```
2016-12-08 13:12:53.832 INFO  [main] io.github.retz.db.Database - No user found: creating admin user 
Exception in thread "main" java.lang.RuntimeException: Key cannot be null....
	at io.github.retz.cli.FileConfiguration.getUser(FileConfiguration.java:120)
	at io.github.retz.db.Database.init(Database.java:91)
	at io.github.retz.scheduler.Launcher.run(Launcher.java:68)
	at io.github.retz.scheduler.Launcher.main(Launcher.java:57)
```

I guess it should rather fail saying "retz.access.key must be specified in the configuration file" or similar.

**Comment by tgpfeiffer** [comment]
Similarly, on the client it should tell the user that `retz.access.key` is required; currently it fails with a 403 code.

**Comment by kuenishi** [comment]
753ab4868fda make it more graceful, throwing proper exception claiming lacking 'retz.access.key'.

```
ERROR retz.access.key should always be present in your configuration file
Exception in thread "main" java.lang.IllegalArgumentException: Authentication access key lacking
        at io.github.retz.cli.FileConfiguration.<init>(FileConfiguration.java:81)
        at io.github.retz.cli.FileConfiguration.<init>(FileConfiguration.java:62)
        at io.github.retz.cli.FileConfiguration.<init>(FileConfiguration.java:58)
        at io.github.retz.cli.ClientCLIConfig.<init>(ClientCLIConfig.java:34)
        at io.github.retz.cli.Launcher.parseConfiguration(Launcher.java:120)
        at io.github.retz.cli.Launcher.execute(Launcher.java:61)
        at io.github.retz.cli.Launcher.main(Launcher.java:54)
```

**Comment by tgpfeiffer** [comment]
Yes, this looks better to me.
